### ISSUE TITLE
Add support for common help command-line switches

### ISSUE THREAD

**Issue by RicoLeNecro** [jackdp/Quick-Change-Resolution#1]
Hello there.

As documented on https://github.com/jackdp/Quick-Change-Resolution#run-time-parameters the program supports some run-time parameters.

It would be nice if calling it with the traditional help parameters that are "/?",  "-?" and "--help" would display that list of supported run-time parameters, along with a short description of what the program is for :)

As of version 1.0, calling it with either "/?", "-?" or "--help" opens a window that states "Unregistered option  (Position: 1)"

**Comment by jackdp** [comment]
Something like this?

### Help
`QuickChangeResolution.exe -?`

![image](https://user-images.githubusercontent.com/22514813/133942425-7d175dd4-4efe-460e-b0f0-1958fe043afb.png)

### Invalid option
`QuickChangeResolution.exe -abcd`

![image](https://user-images.githubusercontent.com/22514813/133942470-1092c68d-dd4e-472c-9de2-2ea72b0852c9.png)

**Comment by RicoLeNecro** [comment]
Yes, should be good :)

**Comment by jackdp** [comment]
Thank you, added in version 1.1
