### ISSUE TITLE
Ensure that the program's window is visible enough?

### ISSUE THREAD

**Issue by RicoLeNecro** [jackdp/Quick-Change-Resolution#2]
Hi,

Just to see what would happen I've tested (under Windows 10 v21H1 x64) the following:

1 - on a somewhat high definition monitor (for example a "4k" one), open the program and move its window to the lower right side of the desktop, then close it.

2 - then, while Quick-Change-Resolution is not running, use Windows' built-in way to change the desktop's resolution, and set it to something pretty low (like 1280x720 for example), such that the last position coordinates of the upper left corner of the window is clearly outside of the desktop's new visible area.

3 - start Quick-Change-Resolution again

What I noticed when doing this is that then, a very small part (the top left) of the program's window is visible at the bottom right of the desktop, which makes it barely noticeable, especially if the task bar is shown.

I suggest that, when starting the program, if the current desktop resolution is such that the coordinates for any corner of the program's window are outside of the visible area, then the window should either be centered or moved to the 0,0 coordinates, so that it's much more visible.

**Comment by jackdp** [comment]
Correcting window position added in version 1.1. Thank you.

**Comment by RicoLeNecro** [comment]
Yup, looks solved :)
